#!/usr/bin/env ruby
# frozen_string_literal: true

require 'nya_pr'

begin
  NyaPr.run
rescue OptionParser::ParseError, NyaPr::Error => e
  warn "nya-pr: #{e.message}"
  exit 1
rescue Interrupt
  warn "\nnya-pr: interrupted"
  exit 130
end
